force-app/main/default/objects/Question_Answer__c/Question_Answer__c.object-meta.xml
<CustomObject>
    <label>Question Answer</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Answer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question_Answer__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipName>Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question_Answer__c/fields/Unit_History__c.field-meta.xml
<CustomField>
    <fullName>Unit_History__c</fullName>
    <label>Unit History</label>
    <referenceTo>Unit_History__c</referenceTo>
    <relationshipLabel>Question Answer</relationshipLabel>
    <relationshipName>Question_Answer</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit_History__c/Unit_History__c.object-meta.xml
<CustomObject>
    <label>Unit History</label>
    <nameField>
        <displayFormat>UH-{0000}</displayFormat>
        <label>Unit Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_History__c/fields/TriesNumber__c.field-meta.xml
<CustomField>
    <fullName>TriesNumber__c</fullName>
    <label>TriesNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit_History__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Unit_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_History__c/fields/Unit_Completed__c.field-meta.xml
<CustomField>
    <fullName>Unit_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unit Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UnitHistoryTrigger.cls
public with sharing class UnitHistoryTrigger {

    public List<Unit_History__c> newUnitHistoryList;
    public Map<Id, Unit_History__c> oldUnitHistoryMap;

    public UnitHistoryTrigger(List<Unit_History__c> newUnitHistoryList, Map<Id, Unit_History__c> oldUnitHistoryMap) {
        this.newUnitHistoryList = newUnitHistoryList;
        this.oldUnitHistoryMap = oldUnitHistoryMap;
        
    }
    
    public void onBeforeUpdate(){

        List <Unit_History__c> filterList = new List <Unit_History__c>();
        for(Unit_History__c  finalList : this.newUnitHistoryList){
            if(finalList.Status__c == 'Answered' && this.oldUnitHistoryMap.get(finalList.id).Status__c == 'Draft'){
                filterList.add(finalList);
        }
    }
    validateAnswer(filterList);
}

public static void validateAnswer (List<Unit_History__c> filterList){

    Map<Id, Unit_History__c> unitHistoryMap = new Map<Id, Unit_History__c>([
            SELECT Id, Unit__r.Points__c, (
                SELECT Id, Option__r.IsCorrect__c
                FROM Question_Answer__r
            )
            FROM Unit_History__c
            WHERE Id IN : filterList
        ]);

        for (Unit_History__c unitHistory: filterList){
            Integer count = 0;
            
            
            for (Question_Answer__c questionAnswer: unitHistoryMap.get(unitHistory.Id).Question_Answer__r){
                Boolean isCorrect = questionAnswer.Option__r.IsCorrect__c;
                if (isCorrect) {
                    count++;
                }
            }
            if(count == unitHistoryMap.get(unitHistory.Id).Question_Answer__r.size()){
                unitHistory.Status__C = 'Success';
                unitHistory.Unit_Completed__c = true;
                if(unitHistory.TriesNumber__c == 1){
                    unitHistory.Points__c = unitHistoryMap.get(unitHistory.id).Unit__r.Points__c;
                }else if(unitHistory.TriesNumber__c == 2){
                    unitHistory.Points__c = unitHistoryMap.get(unitHistory.id).Unit__r.Points__c/2;
                }else{
                    unitHistory.Points__c = unitHistoryMap.get(unitHistory.id).Unit__r.Points__c/4;
                }
            }else{
                unitHistory.Status__C = 'Fail';
            }
        }

}

    
}