force-app/main/default/objects/Module_History__c/Module_History__c.object-meta.xml
<CustomObject>
    <label>Module History</label>
    <nameField>
        <displayFormat>MH-{0000}</displayFormat>
        <label>Module Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modules History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_History__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <label>Total Points</label>
    <summarizedField>Unit_History__c.Points__c</summarizedField>
    <summaryForeignKey>Unit_History__c.Module_History__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Module_History__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Modules_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ModuleHistoryTrigger.cls
public class ModuleHistoryTrigger {
    
    private Map<Id, User> userMap;
	
    public void onAfterUpsert(List<Module_History__c> moduleHistories) {    
        this.setUsers();
        this.clean();
        this.sumTotalPointPerModule(moduleHistories);      
        update userMap.values();       
    }
    
    private void setUsers() {
        userMap = new Map<Id, User>([
            SELECT Id, Total_Points__c
            FROM User
        ]);
    }
    
    private void clean() {
        for(User currentUser: userMap.values()) {
            currentUser.Total_Points__c = 0;
        }
    }
    
    private void sumTotalPointPerModule(List<Module_History__c> moduleHistories) {
        for(Module_History__c moduleHistory:  moduleHistories) {
            Id userId = moduleHistory.User__c;
            User currentUser = userMap.get(userId);
            currentUser.Total_Points__c += moduleHistory.Total_Points__c;
            userMap.put(userId, currentUser);  
        }
    }
    
    
}