force-app/main/default/objects/Module__c/fields/Total_Time_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Total_Time_Estimate__c</fullName>
    <label>Total Time Estimate</label>
    <summarizedField>Unit__c.Time_Estimate__c</summarizedField>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Module_History__c/Module_History__c.object-meta.xml
<CustomObject>
    <label>Module History</label>
    <nameField>
        <displayFormat>MH-{0000}</displayFormat>
        <label>Module Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modules History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_History__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipName>Modules_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module_History__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Modules_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trail__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <summarizedField>TrailModule__c.Points__c</summarizedField>
    <summaryForeignKey>TrailModule__c.Trail__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Trail__c/fields/Time_Estimated__c.field-meta.xml
<CustomField>
    <fullName>Time_Estimated__c</fullName>
    <label>Time Estimated</label>
    <summarizedField>TrailModule__c.Time_Estimated__c</summarizedField>
    <summaryForeignKey>TrailModule__c.Trail__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TrailModule__c/TrailModule__c.object-meta.xml
<CustomObject>
    <label>TrailModule</label>
    <nameField>
        <label>TrailModule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrailModules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TrailModule__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>TrailModules</relationshipLabel>
    <relationshipName>TrailModules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TrailModule__c/fields/Time_Estimated__c.field-meta.xml
<CustomField>
    <fullName>Time_Estimated__c</fullName>
    <label>Time Estimated</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TrailModule__c/fields/Trail__c.field-meta.xml
<CustomField>
    <fullName>Trail__c</fullName>
    <label>Trail</label>
    <referenceTo>Trail__c</referenceTo>
    <relationshipLabel>TrailModules</relationshipLabel>
    <relationshipName>TrailModules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Time_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Time_Estimate__c</fullName>
    <label>Time Estimate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit_History__c/Unit_History__c.object-meta.xml
<CustomObject>
    <label>Unit History</label>
    <nameField>
        <displayFormat>UH-{0000}</displayFormat>
        <label>Unit Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_History__c/fields/Module_History__c.field-meta.xml
<CustomField>
    <fullName>Module_History__c</fullName>
    <label>Module History</label>
    <referenceTo>Module_History__c</referenceTo>
    <relationshipLabel>Unit History</relationshipLabel>
    <relationshipName>Unit_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit_History__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Unit_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_History__c/fields/Unit_Completed__c.field-meta.xml
<CustomField>
    <fullName>Unit_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unit Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TrailWrapper.cls
public class TrailWrapper {

    @AuraEnabled
    public Trail__c trail {get; set;}
    @AuraEnabled
    public List<Module__c> modules {get; set;}
    @AuraEnabled
    public Set<Id> passedModuleIds {get; set;}
    @AuraEnabled
    public Set<Id> passedUnitIds {get; set;}
    @AuraEnabled
    public Integer progressTrail {get; set;}

    //private Id trailId;

    public TrailWrapper(Trail__c trail, List<Module__c> modules, Set<Id> passedModuleIds, Set<Id> passedUnitIds) {
        this.trail = trail;
        this.modules = modules;
        this.passedModuleIds = passedModuleIds;
        this.passedUnitIds = passedUnitIds;
    }

    @AuraEnabled(cacheable=true)
    public static TrailWrapper getTrailWrapper(Id trailId){
    TrailWrapper trailWrap = new TrailWrapper([
                                                  SELECT Name, 
                                                  Description__c, 
                                                  Points__c,
                                                  Time_Estimated__c
                                                  FROM Trail__c 
                                                  WHERE Id =: trailId
                                                  
                                                  ],
         getModules(trailId), getModuleIdsCompleted(trailId), getUnitIdsCompleted(trailId));
        
        return trailWrap;
    }
    
    private static List<Module__c> getModules(Id trailId){
    	Set<Id> moduleIds = new Set<Id>();

        List<TrailModule__c> trailModules = [
            SELECT Module__c
            FROM TrailModule__c
            WHERE Trail__c =: trailId
        ];

        for (trailModule__c trailModule: trailModules){
            moduleIds.add(trailModule.Module__c);
        }

        return [SELECT Name,Total_Time_Estimate__c, Points__c, (SELECT Name, Points__c, Time_Estimate__c FROM Units__r) FROM Module__c WHERE Id in : moduleIds];
    }
    
    private static Set<Id> getModuleIdsCompleted(Id trailId){
    	List<Module_History__c> moduleHistories = [
            										SELECT Module__c
            										FROM Module_History__c
            										WHERE Status__c = 'Completed' AND 
                									Module__c in : getModules(trailId) AND
                									User__c =: UserInfo.getUserId()
        											];

        Set<Id> completedModuleIds = new Set<Id>();
        for (Module_History__c moduleHistory : moduleHistories) {
            completedModuleIds.add(moduleHistory.Module__c);
        }
        return completedModuleIds;
    }
    
    
    private static Set<Id> getUnitIdsCompleted(Id trailId){
    	List<Unit_History__c> unitHistories = [
        										SELECT Unit__c
        										FROM Unit_History__c
        										WHERE Unit_Completed__c = true AND 
        										Unit__r.Module__c in : getModules(trailId) AND
        										Module_History__r.User__c =: UserInfo.getUserId()
        										];
		Set<Id> completedUnitIds = new Set<Id>();
        for (Unit_History__c unitHistory : unitHistories) {
        completedUnitIds.add(unitHistory.Unit__c);
        }
        
        return completedUnitIds;
    }
    
    
}